name: ansible_role_tags
on:
  push:
    tags:
      - '*'
jobs:
  config-yaml:
    name: config.yaml
    runs-on: arm64
    outputs:
      config: ${{ steps.config.outputs.config }}
    steps:
      - uses: actions/checkout@v4
      # https://github.com/chrisdickinson/setup-yq/blob/latest/action.yml
      - uses: chrisdickinson/setup-yq@v1.0.1
        name: yq=v4.43.1
        with:
          yq-version: v4.43.1
      - name: yq=version
        run: yq --version
      
      - name: jq=1.7
        uses: dcarbone/install-jq-action@v2
        with:
          version: 1.7
      
      - name: export=config
        id: config
        run: echo "config=$(yq -oj '.' config.yaml | jq -cr)" >> $GITHUB_OUTPUT
  ansible-role-tags:
    name: ${{ matrix.build.os }}-${{ matrix.build.arch }}
    needs: config-yaml
    runs-on: ${{ matrix.build.runs_on }}
    strategy:
      fail-fast: false
      matrix:
        build: ${{ fromJSON(needs.config-yaml.outputs.config).builds }}
    container:
      image: ${{ fromJSON(needs.config-yaml.outputs.config).upstream.repo }}:${{ fromJSON(needs.config-yaml.outputs.config).upstream.tag }}-${{ matrix.build.os }}
    steps:
      - name: checkout=self
        uses: actions/checkout@v4
      - name: task=latest
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
          export PATH=$(pwd)/bin:$PATH
      - name: task=version
        run: ./bin/task --version
      - name: checkout=taskfiles@feature/arm
        uses: actions/checkout@v4
        with:
          path: taskfiles
          repository: bradfordwagner/taskfiles
          ref: feature/arm
      
      - uses: docker/login-action@v3
        name: login=ghcr.io
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: task=branches
        run: task -t ./taskfiles/tasks/ansible_role.yml
  ansible-role-tags-publish:
    name: publish
    needs: [config-yaml, ansible-role-tags]
    runs-on: ubuntu-latest
    steps:
      - name: checkout=self
        uses: actions/checkout@v4
      - name: galaxy_publish
        uses: robertdebock/galaxy-action@1.2.0
        with:
          galaxy_api_key: ${{ secrets.GALAXY_TOKEN }}
          git_branch: ${{ github.ref_name }}
