name: ansible_role
on: push
jobs:
  ansible-role:
    runs-on: ubuntu-latest
    container:
      image: quay.io/bradfordwagner/ansible:3.6.2-debian_bookworm
    steps:
      # - name: my-step
      #   run: echo "Hello World!"
      - name: Setup go-task
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.35.1
      - name: task version
        run: task --version
      - uses: actions/checkout@v4
        with:
          repository: bradfordwagner/taskfiles
          path: tasks
      - name: list files
        run: |
          ls -lh
          pwd
      - name: my-step
        run: task -t ./tasks/tasks/ansible_role.yml
