name: ansible_role
on:
  - push
  - workflow_dispatch
jobs:
  ansible-role:
    strategy:
      fail-fast: false
      matrix:
        os:
          - alpine_3.16
          - alpine_3.17
          # - archlinux_latest
          - debian_bookworm
          - debian_bullseye
          - ubuntu_focal
          # - ubuntu_kinetic
          - ubuntu_lunar
        tag: [3.6.2]
    runs-on: ubuntu-latest
    container:
      image: quay.io/bradfordwagner/ansible:${{ matrix.tag }}-${{ matrix.os }}
    steps:
      - name: checkout=self
        uses: actions/checkout@v4
      - name: task=3.35.1
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.35.1
      - name: checkout=taskfiles
        uses: actions/checkout@v4
        with:
          path: taskfiles
          repository: bradfordwagner/taskfiles
      - name: task=branches
        run: task -t ./taskfiles/tasks/ansible_role.yml
