name: ansible_role_tags
on:
  push:
    tags:
      - '*'
env:
  version: ${{ github.ref_name }}
jobs:
  product:
    name: product
    runs-on: arm64
    outputs:
      product: ${{ steps.config.outputs.product }}
    steps:
      - uses: actions/checkout@v4
      - name: dagger=0.11.8
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.11.8 sh
      - name: dagger=product
        id: config
        run: |
          # write your own scoped version of the following since  is not available at this base level
          # echo product=$(./bin/dagger -m  call product-json --src=. --version=${{ env.version }}) >> $GITHUB_OUTPUT
          echo product=$(./bin/dagger -m github.com/bradfordwagner/dagger-modules/ansible@main call product-json --src=. --version=${version}) >> $GITHUB_OUTPUT
  builds:
    runs-on: ${{ matrix.product.runner }}
    permissions: write-all
    needs: product
    name: ${{ matrix.product.index }}:${{ matrix.product.os }} (${{ matrix.product.arch }})
    strategy:
      fail-fast: false
      matrix:
        product: ${{ fromJSON(needs.product.outputs.product) }}
    steps:
      - uses: actions/checkout@v4
      - name: dagger=0.11.8
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.11.8 sh
      # work around other runner's logging out removing credentials
      # https://github.com/docker/login-action/issues/173#issuecomment-1079688020
      - name: Set DOCKER_CONFIG
        run: |
          id=docker_configs/$(uuidgen)
          mkdir -p $HOME/${id}/.docker
          echo "DOCKER_CONFIG=$HOME/${id}/.docker" >> $GITHUB_ENV
      - uses: docker/login-action@v3
        name: login=ghcr.io
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
          logout: false
      - name: dagger=build
        run: |
          ./bin/dagger -m github.com/bradfordwagner/dagger-modules/ansible@main call build \
            --src=. \
            --index=${{ matrix.product.index }} \
            --version=${version} \
            --isDev=false \
            --flavor=role
  ansible-role-tags-publish:
    name: publish
    needs: builds
    runs-on: ubuntu-latest
    steps:
      - name: checkout=self
        uses: actions/checkout@v4
      - name: galaxy_publish
        uses: robertdebock/galaxy-action@1.2.0
        with:
          galaxy_api_key: ${{ secrets.GALAXY_TOKEN }}
          git_branch: ${{ github.ref_name }}
