name: ansible_role_branches
on:
  - push
  - workflow_dispatch
jobs:
  ansible-role-branches-publish:
    name: publish
    # needs: [config-yaml, ansible-role-branches]
    runs-on: ubuntu-latest
    steps:
      - name: checkout=self
        uses: actions/checkout@v4
      - name: galaxy
        uses: robertdebock/galaxy-action@1.2.0
        with:
          galaxy_api_key: ${{ secrets.GALAXY_TOKEN }}
          git_branch: ${{ github.ref }}
      # - uses: chrisdickinson/setup-yq@v1.0.1
      #   name: yq=v4.43.1
      #   with:
      #     yq-version: v4.43.1
      # - name: fix=git://safedir
      #   run: git config --system --add safe.directory '*'
      # - name: task=branches
      #   run: task -t ./taskfiles/tasks/ansible_role.yml publish_role_to_galaxy \
      #     token="${{ secrets.GALAXY_TOKEN }}"
