name: ansible_role
on: push
jobs:
  ansible-role:
    runs-on: ubuntu-latest
    container:
      image: quay.io/bradfordwagner/ansible:3.6.2-debian_bookworm
    steps:
      - name: Setup go-task
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.35.1
      - name: task version
        run: task --version
      - name: checkout taskfiles
        uses: actions/checkout@v4
        with:
          path: taskfiles
          repository: bradfordwagner/taskfiles
      - uses: actions/checkout@v4
      - name: list files
        run: |
          ls -lhRa
          pwd
          tree
      - name: my-step
        run: task -t ./taskfiles/tasks/ansible_role.yml
